---
# Playbook to Backup all config and produce show outputs

- hosts : localhost
  gather_facts: False
 
  
  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.weekday }}"

   - name: Create Directory ~/NAFE/backups/{{hostvars.localhost.DTG}} 
     file: 
      path: ~/NAFE/backups/{{hostvars.localhost.DTG}}
      state: directory
  


- hosts : CSR_Routers
  tasks:
    - name: Backup config
      ios_command:
        commands: show run
      register: config

    - name: Save Output to File
      copy:
        content: "{{config.stdout[0]}}"
        dest: "~/NAFE/backups/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-config.txt"
    

- hosts: CSR_Routers
  connection: local
  gather_facts: false

  vars:
    command_list:      
      - show cdp neigh 
      - show ip ospf int brief 
      - show ip ospf neigh 
      - show cdp neighbors detail
      - show clock
      - show ip arp
      - show ip interface brief | exc admin
    #- show etherchannel summary 
    #  - show environment all
    #  - show users
    #  - show boot
    # - show int status | inc connected

  tasks:
   - name: Run the SHOW commands and save output 
     ios_command:
       commands: "{{ command_list }}"
     register: showoutput

   - name: "Put all the files together into one nice text file"
     template: 
       src: ./template.j2 
       dest: "~/NAFE/backups/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-showoutput.txt"
       
