- hosts: CSR_Routers
  connection: "network_cli"
  gather_facts: False

  tasks:
  - name: show run on devices
    ios_config:
       commands: show run
    register: config

  - name: get current configured ntp servers
    set_fact: _servers="{{ config.stdout[0] | regex_findall('^ntp server (\S+)', multiline=True) }}"

  - name: remove old ntp servers
    ios_config:
        lines: 
             - "no ntp server {{ item }}"
    with_items: "{{ _servers }}"

  - name: Configure new NTP server
    ios_config:
      lines:  ntp server 4.5.6.7
